packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.8.2
  "@orpc/server": ^1.9.0
  "@orpc/openapi": ^1.9.0
  "@orpc/zod": ^1.9.0
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  zod: ^4.1.12
  typescript: ^5.8.2
  tsdown: ^0.15.5
  "@orpc/client": ^1.9.0
  vitest: ^3.2.4
  "@vitest/coverage-istanbul": ^3.2.4
