/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as CheckEmailIndexRouteImport } from './routes/check-email/index'
import { Route as landingpageIndexRouteRouteImport } from './routes/(landingpage)/index/route'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as ProtectedAppIndexRouteRouteImport } from './routes/_protected.app/index/route'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailIndexRoute = CheckEmailIndexRouteImport.update({
  id: '/check-email/',
  path: '/check-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const landingpageIndexRouteRoute = landingpageIndexRouteRouteImport.update({
  id: '/(landingpage)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedAppIndexRouteRoute = ProtectedAppIndexRouteRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof landingpageIndexRouteRoute
  '/check-email': typeof CheckEmailIndexRoute
  '/app': typeof ProtectedAppIndexRouteRoute
  '/login': typeof AuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof landingpageIndexRouteRoute
  '/check-email': typeof CheckEmailIndexRoute
  '/app': typeof ProtectedAppIndexRouteRoute
  '/login': typeof AuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/(landingpage)/': typeof landingpageIndexRouteRoute
  '/check-email/': typeof CheckEmailIndexRoute
  '/_protected/app/': typeof ProtectedAppIndexRouteRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/check-email' | '/app' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/check-email' | '/app' | '/login'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/(landingpage)/'
    | '/check-email/'
    | '/_protected/app/'
    | '/_auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  landingpageIndexRouteRoute: typeof landingpageIndexRouteRoute
  CheckEmailIndexRoute: typeof CheckEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email/': {
      id: '/check-email/'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landingpage)/': {
      id: '/(landingpage)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingpageIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/app/': {
      id: '/_protected/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ProtectedAppIndexRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAppIndexRouteRoute: typeof ProtectedAppIndexRouteRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppIndexRouteRoute: ProtectedAppIndexRouteRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  landingpageIndexRouteRoute: landingpageIndexRouteRoute,
  CheckEmailIndexRoute: CheckEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
